import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function PostsLayout({ children }) {
  return (
    <>
      <div>some else</div>
      <div className={inter.className}>{children}</div>
    </>
    
  )
}
